[tool.ruff]
target-version = "py311"
line-length = 88
src = ["app"]

[tool.ruff.lint]
select = [
    "E", "W", "F", "I", "B", "UP", "N", "ANN", "BLE", "C4", "PIE",
    "PLC", "PLE", "PLW", "RUF"
]
ignore = [
    "ANN401",
    "BLE001",
    "RUF012",
    "E501"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"